config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'messages#index'
  post '/messages/like', to: 'messages#like', as: 'message_like'
  post '/messages/dislike', to: 'messages#dislike', as: 'message_dislike'
  resources :messages

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dislike.rb
class Dislike < ApplicationRecord
  belongs_to :message
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :message # Ok, techniquement, c'est juste. Etrange mais juste...
end

app/models/message.rb
class Message < ApplicationRecord
  has_many :likes
  has_many :dislikes # Mmmmh, c'est curieux. Je vais essayer de vous suivre mais votre conception est... étrange

  belongs_to :user # Bien

  validates :content, presence: true # BIEN ! Merci d'être le premier TP où je vois (enfin) cette validation
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # Dommage... manque juste le has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Manque authenticate_user!
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = Message.new
    @like = Like.new
    @dislike = Dislike.new
    if current_user
      @messages = Message.last(20).reverse
    else
      redirect_to user_session_path
    end
  end

  def like
    @like = Like.new(like_params)
    @like.save
    redirect_to root_path
  end

  def dislike
    @dislike = Dislike.new(dislike_params)
    @dislike.save
    redirect_to root_path
  end

  def create
    @post = Message.new(message_params)

    @post.save
    redirect_to root_path
  end

  private

  def message_params
    params.require(:message).permit(
        :content
    ).merge(user_id: current_user.id)
  end

  def like_params
    params.require(:like).permit(
        :message_id
    )
  end

  def dislike_params
    params.require(:dislike).permit(
        :message_id
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">

  <!-- Compiled and minified JavaScript -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<nav>
  <div class="nav-wrapper">
    <%= link_to root_path, class: 'brand-logo left' do %> <i class="fab fa-twitter white-text"></i> Twitter
    <% end %>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><%= link_to 'Accueil', root_path %></li>
      <li><%= link_to 'Se déconnecter', destroy_user_session_path, method: :delete %></li>
    </ul>
  </div>
</nav>
<main>
  <%= yield %>
</main>
<div class="blue">
  <div class="row">
    <div class="col l6 s12">
      <h5 class="white-text" style="text-align: right">
        ©2018 Benjamin L'HONNEN
      </h5>
    </div>
    <div class="col l6 s12">
      <h5 class="white-text">Using</h5>
      <ul>
        <li><a class="grey-text text-lighten-4" target="_blank" href="https://materializecss.com/">Materialize</a></li>
        <li><a class="grey-text text-lighten-4" target="_blank" href="https://fontawesome.com/?from=io">Font-Awesome</a></li>
        <li><a class="grey-text text-lighten-4" target="_blank" href="https://fonts.google.com/">Google-Font</a></li>
        <li><a class="grey-text text-lighten-4" target="_blank" href="https://rubyonrails.org/">Rails</a></li>
      </ul>
    </div>
  </div>
</div>
</body>
</html>

app/views/messages/index.html.erb
<%= form_tag messages_path, method: :post, class: 'row' do %>
  <div class="input-field col s10">
    <%= text_area_tag 'message[content]', @message.content, id: 'comment', class: 'materialize-textarea' %>
    <%= label_tag 'Quoi de neuf ?' %>
  </div>
  <%= submit_tag 'Tweeter', for: 'comment', class: 'btn blue white-text col s2' %>
<% end %>

<div class="row">
  <% @messages.each do |message| %>
    <div class="col s12">
      <div class="card card-relative">
        <div class="card-content">
          <h5><%= message.user.email %></h5>
          <h4><%= message.content %></h4>
          <div class="row like">
            <%= form_tag message_like_path, method: :post, class: 'col s6 row' do %>
              <%= hidden_field_tag 'like[message_id]', message.id %>
              <%= button_tag '', class: 'btn green white-text col s12 flex flex-center h40' do %>
                <span class="fs-16"><%= message.likes.length %></span> <i class="fas fa-thumbs-up fs-16"></i>
              <% end %>
            <% end %>
            <%= form_tag message_dislike_path, method: :post, class: 'col s6 row' do %>
              <%= hidden_field_tag 'dislike[message_id]', message.id %>
              <%= button_tag '', class: 'btn red white-text col s12 flex flex-center h40' do %>
                <span class="fs-16"><%= message.dislikes.length %></span> <i class="fas fa-thumbs-down fs-16"></i>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>